"""empty message

Revision ID: 1743f5d54bf4
Revises: 2eb2bf6f1c30
Create Date: 2015-11-09 17:41:28.161656

"""

# revision identifiers, used by Alembic.
revision = '1743f5d54bf4'
down_revision = '2eb2bf6f1c30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
